name: Build, Upload, and Sync

on:
  release:
    types: [published] # 自动触发同步

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      # 设置时区为亚洲/上海
      - name: Set Timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      # 检出代码
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      # 获取原仓库的预发行版属性
      - name: Get Original Repository Pre-release Property
        id: pre_release
        run: |
          echo "IS_PRERELEASE=$(if [ "${{ github.event.release.prerelease }}" = true ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_OUTPUT

      # 赋予 Gradlew 执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 同时编译 Normal 和 Compatible APK
      - name: Build Normal and Compatible APKs
        run: |
          ./gradlew assembleNormalRelease assembleCompatibleRelease -Pversion=${{ github.ref_name }}

      - name: Sign Normal APK
        id: sign_normal_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/normal/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Sign Compatible APK
        id: sign_compatible_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/compatible/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Generate APKS Checksum
        run: |
          sha256sum ${{ steps.sign_normal_apk.outputs.signedFile  }} > CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256
          sha256sum ${{ steps.sign_compatible_apk.outputs.signedFile }} > CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256

      - name: Upload Assets to Source Release
        uses: softprops/action-gh-release@v2
        with:
          name: Sesame-${{ github.event.release.tag_name || github.ref_name }} # 发布的名称。默认为标签名称
          files: |
            ${{ steps.sign_normal_apk.outputs.signedFile }}
            ${{ steps.sign_compatible_apk.outputs.signedFile }}
            CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256
            CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256
          tag_name: ${{ github.ref_name }}
          draft: false
          append_body: true
          generate_release_notes: true
          body: |
            > ## 下载说明
              * Normal 为正常版本,适用于Android 8.0及以上的系统
              * Compatible 为兼容版本,适用于Android 7.0及以下的系统,最低支持Android 5.1
            > ## 墙内更新
              [抗揍云-LanZou](https://fansirs.lanzoue.com/b011kv6pwd) 密码:`9527`
              [Alist分流-LanZou](https://alist.798356.xyz/LanZou/Sesame-TK) 密码:`9527`
              [Alist分流-ALiYun](https://alist.798356.xyz/AliYun/share/Sesame-TK) 密码:`9527`

      - name: Sync Release to Target Repository
        uses: softprops/action-gh-release@v2
        with:
          repository: Xposed-Modules-Repo/fansirsqi.xposed.sesame # 目标仓库的拥有者和仓库名称
          name: Sesame-${{ github.event.release.tag_name || github.ref_name }} # 发布的名称。默认为标签名称
          files: |
            ${{ steps.sign_normal_apk.outputs.signedFile }}
            ${{ steps.sign_compatible_apk.outputs.signedFile }}
            CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256
            CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256
          token: ${{ secrets.TARGET_REPO_PAT }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ steps.pre_release.outputs.IS_PRERELEASE }}
          append_body: false
          make_latest: true
          body: |
            📦 本 Release 同步自源仓库 [Sesame-TK](https://github.com/${{ github.repository }})
            ✨ **更新内容**:
            ${{ github.event.release.body || '无更新说明' }}

      - name: TgBot Notification & Upload
        run: |
          # 发送带文件的通知消息
          curl -F document=@${{ steps.sign_normal_apk.outputs.signedFile }} -F document=@${{ steps.sign_compatible_apk.outputs.signedFile }} -F document=@CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256 -F document=@CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256 "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.TG_CHAT_ID }}&caption=📦 新版本发布 [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }})%0A%0A✨ 更新内容：%0A${{ github.event.release.body }}%0A%0A🔗 下载地址：%0A${{ github.event.release.html_url }}%0A抗揍云：https://fansirs.lanzoue.com/b011kv6pwd 密码：9527&parse_mode=Markdown"
